# Generated by Django 4.0.2 on 2022-02-24 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_ninjas_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ninja',
            old_name='dojos',
            new_name='dojo',
        ),
    ]
