# Generated by Django 4.0.2 on 2022-02-24 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_ninjas_app', '0002_rename_dojos_ninja_dojo'),
    ]

    operations = [
        migrations.AddField(
            model_name='dojos',
            name='desc',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
