# Generated by Django 4.0.2 on 2022-02-24 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_ninjas_app', '0006_dojos_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dojos',
            name='desc',
        ),
    ]
